# Setup
title:        My Develop Blog
tagline:      日々の開発についてのメモをブログにしました。
baseurl:      ""
paginate:     1
locale:       "ja"

# About/contact
author:
  name:       quin001cunx
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
